### ISSUE TITLE
Available is indistinguishable from Unavailable

### ISSUE THREAD

**Issue by tko** [system-fonts/modern-font-stacks#1]
...when you're red-green color blind.

For example strike through would make Unavailable clearly different, kind of similar to underlining on the "Currently In Use" variant. Maybe little extreme though.

**Comment by Abdull** [comment]
I saw the Hacker News discussion regarding the textual coloring of font names ( https://news.ycombinator.com/item?id=35169145  ).

Can you explain what red vs. green, and not-underlined vs. underlined means? I didn't find any information about these properties. 

Here is a screenshot of how my smartphone rendered https://modernfontstacks.com/#font-stacks just a couple minutes ago as of this writing:

![Screenshot_20230315-211739](https://user-images.githubusercontent.com/529862/225433092-d4c1bbe2-274b-4a69-8170-eee12be7fca2.png)

And maybe adding a commit hash / version information to the website is also a great idea.

**Comment by danklammer** [comment]
This has been updated. We have dotted underline for "available" fonts and new color is blue. Thanks all!
![new-color-pallette](https://user-images.githubusercontent.com/1743221/225470934-4a0b5e0b-02eb-4aab-9dca-99e499d0fc97.png)
