### ISSUE TITLE
Industrial missing font weights on MacOS

### ISSUE THREAD

**Issue by willfarrell** [system-fonts/modern-font-stacks#10]
Currently Mac is selecting `'DIN Alternate'` when viewed on MacOS 13.2.1. This font doesn't have additional font weights. Is there an equivalent that can be used instead?

PS Thanks for putting this site together, the more designed focused members of our team are excited to have more font option to choose from.

**Comment by danklammer** [comment]
@willfarrell That one is limited on macOS and iOS. I really recommend using the medium weight and use it as display font like for headlines.

The next best alternative for this classification on mac/iOS is probably `'Avenir Next Condensed'` or `'Apple SD Gothic Neo'`. Both are a little more humanistic than others in the stack, but with many weights.

![Avenir Next Condensed](https://user-images.githubusercontent.com/1743221/227273763-563b52ff-9652-4c27-87b8-be1ed6561d84.png)

![Apple SD Gothic Neo](https://user-images.githubusercontent.com/1743221/227273767-37a860fd-2ba7-45fb-8c01-8c8ab25c35b5.png)

**Comment by willfarrell** [comment]
Thanks!
