### ISSUE TITLE
add iOS-font to stack "industrial"

### ISSUE THREAD

**Issue by jochmann** [system-fonts/modern-font-stacks#11]
the current font stack does not address iOS.
perhaps it would be prudent to clarify that the sans-serif fallback resolves to San Francisco (and that San Francisco fits the font-stack)?

**Comment by danklammer** [comment]
@jochmann Good Catch. DIN Alternate is also on iOS. I will clarify in the docs.

![ios-din](https://user-images.githubusercontent.com/1743221/227782851-5cc0ed7b-aa6a-440a-b644-fb90cacb46a5.jpg)

**Comment by danklammer** [comment]
I may rework this stack to use SF Compact for macOS & iOS since DIN Alternate only has one weight. Other comments here:
https://github.com/system-fonts/modern-font-stacks/issues/10#issuecomment-1481552011
