### ISSUE TITLE
Installed fonts are not shown in your web site as preview

### ISSUE THREAD

**Issue by lobaluna** [system-fonts/modern-font-stacks#13]
I'm sorry if I'm misguided, but many fonts mentioned in your web site are not shown in the preview article, nor in the rest of the web site. Many of those fonts are already installed in my system, I use them in projects, etc.

However, your site shows (underlined fonts) that the current font that's in use are the very basic font of each category: san-serif, monospace, serif.

So maybe I don't get it, or something is wrong.

**Comment by danklammer** [comment]
@lobauna Interesting. The only font that will be visible if the first available in the stack. Can I ask what OS you are using? All the fonts in these stacks are designed to use pre-installed system fonts, so user installed fonts may or may not work depending on the font alias / postscript name.

**Comment by lobaluna** [comment]
@danklammer Sorry for the delay. I've been absent for a while.
I use Mabox, which is a spinoff of Manjaro. I'll be happy to explore the alias/postscript names of fonts... if you tell how to do it.
