### ISSUE TITLE
MFS for TailwindCSS

### ISSUE THREAD

**Issue by BorisAnthony** [system-fonts/modern-font-stacks#17]
Found myself wanting to use this awesome stuff in a little project I am using TailwindCSS with.
So I quickly put this together:
https://github.com/BorisAnthony/mfs-tailwind
In case anyone else wants/needs it.
(Feedback welcome. Just started with TW so may have not done it the best way or something…)
Thank you in any case. Very handy!

**Comment by BorisAnthony** [comment]
Quick update: TailwindCSS showcased some possible changes to their config methods. Not released yet, but I added a section showing how this might look with MFS. 👍
https://github.com/BorisAnthony/mfs-tailwind

**Comment by danklammer** [comment]
This is awesome! I added to the README.
