### ISSUE TITLE
Modern Font Stacks WordPress plugin

### ISSUE THREAD

**Issue by LittleBigThing** [system-fonts/modern-font-stacks#18]
Hi Dan,

Thanks for this great tool! 🥇 
I was surprised to see (after Chris Ferdinandi [sharing this](https://twitter.com/ChrisFerdinandi/status/1676238575661203458?s=20)) what is possible with system fonts. I will definitely fresh up my website with one of these font stacks.

I wanted to let you know that I created this [WordPress plugin](https://github.com/LittleBigThing/Modern-Font-Stacks-for-WP) to enable adding these font stacks to WordPress and choosing them easily in the Site Editor (see screenshot in the repo). And using them more widely, without additional load to the website! 💯 

I hope you like it.

**Comment by danklammer** [comment]
Love this! I added to the README.
