### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by ofaurax** [system-fonts/modern-font-stacks#23]
Most of proposed fonts are not available on Android, so most of the time, the default serif is used.

**Comment by danklammer** [comment]
@ofaurax That is correct. Android does not have many system fonts.
https://android.googlesource.com/platform/frameworks/base/+/master/data/fonts/fonts.xml

**Comment by prakashDiana** [comment]
@danklammer and many Android fonts accessed are only Working in Firefox Browser.
