### ISSUE TITLE
suggestion: move the key to the top

### ISSUE THREAD

**Issue by Rexogamer** [system-fonts/modern-font-stacks#3]
Originally mentioned [here](https://news.ycombinator.com/item?id=35169978) and something that slightly confused me was the significance of the colours/formatting - until you reach the bottom of the page, the key isn't visible. It would probably be s good idea to put it above the font collection. 

(Very handy site, by the way :3)

**Comment by danklammer** [comment]
Makes total sense. This change has been made! Thanks @Rexogamer

**Comment by ret708** [comment]
> Originally mentioned [here](https://news.ycombinator.com/item?id=35169978) and something that slightly confused me was the significance of the colours/formatting - until you reach the bottom of the page, the key isn't visible. It would probably be s good idea to put it above the font collection.
> 
> (Very handy site, by the way :3)
