### ISSUE TITLE
Zeroes

### ISSUE THREAD

**Issue by bwva** [system-fonts/modern-font-stacks#5]
For some users, such as coders, a key criterion for using a font is how it ensures that zeroes are not mistaken for letter 'O's. It would be great if the images of the font stacks included zero: 0123456789 instead of 123456789. Thanks!

**Comment by danklammer** [comment]
Good callout @bwva. I added zeros to the monospace font previews.
https://github.com/system-fonts/modern-font-stacks/commit/10516fd9585545739f25458c381a3fc7221370fe
